### ISSUE TITLE
Contact Section Background Doesn't Cover the whole block

### ISSUE THREAD

**Issue by XiaoJR** [xavierosee/xavierosee.github.io#2]
The "Contact" section background doesn't cover the whole block.

Proposed solution :
Add a "background-size: cover" in css.

From [agency.css](https://github.com/xavierosee/xavierosee.github.io/blob/master/_includes/css/agency.css
) :

Line 662 :
```
section#contact {
    background-color: #010101;
    background-image: url('{{ site.baseurl }}/img/earth-image.jpg');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
```

**Comment by xavierosee** [comment]
@XiaoJR about time I fixed this 😆
